export const disableCorePrefetching = () => {}
export const onClientEntry = () => {}
export const onInitialClientRender = () => {}
export const onPostPrefetchPathname = () => {}
export const onPreRouteUpdate = () => {}
export const onPrefetchPathname = () => {}
export const onRouteUpdate = () => {}
export const onRouteUpdateDelayed = () => {}
export const onServiceWorkerActive = () => {}
export const onServiceWorkerInstalled = () => {}
export const onServiceWorkerRedundant = () => {}
export const onServiceWorkerUpdateFound = () => {}
export const onServiceWorkerUpdateReady = () => {}
export const registerServiceWorker = () => {}
export const replaceHydrateFunction = () => {}
export const shouldUpdateScroll = () => {}
export const wrapPageElement = () => {}
export const wrapRootElement = () => {}
